name: Build Telegram Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Clone Telegram Desktop
      run: |
        git clone --recursive https://${{ secrets.TOKEN }}@github.com/telegramdesktop/tdesktop.git
        cd tdesktop
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        arch: 'win64_msvc2019_64'
        modules: 'qtwebengine'
        
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[17.0,18.0)'
        
    - name: Install Boost
      run: |
        $boostVersion = "1.82.0"
        $boostVersionUnderscores = $boostVersion.Replace(".", "_")
        Invoke-WebRequest -Uri "https://boostorg.jfrog.io/artifactory/main/release/$boostVersion/source/boost_$boostVersionUnderscores.zip" -OutFile "boost.zip"
        Expand-Archive -Path "boost.zip" -DestinationPath "C:\"
        Rename-Item -Path "C:\boost_$boostVersionUnderscores" -NewName "C:\boost"
        cd C:\boost
        .\bootstrap.bat
        .\b2.exe --with-regex --prefix="C:\Program Files (x86)\boost" install
        
    - name: Install dependencies
      run: |
        choco install ninja cmake yasm perl strawberryperl
        choco install -y --force python3
        pip3 install gyp-next
        
    - name: Install Ada
      run: |
        git clone https://${{ secrets.TOKEN }}@github.com/ada-url/ada.git
        cd ada
        mkdir build && cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
        ninja
        ninja install
        
    - name: Configure
      working-directory: tdesktop
      run: |
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DTDESKTOP_API_TEST=ON -DDESKTOP_APP_USE_PACKAGED=OFF -DBOOST_ROOT="C:\Program Files (x86)\boost" -DBoost_INCLUDE_DIR="C:\Program Files (x86)\boost\include" -DBoost_LIBRARY_DIR="C:\Program Files (x86)\boost\lib" ..
        
    - name: Build
      working-directory: tdesktop/build
      run: |
        ninja
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: telegram-desktop
        path: tdesktop/build/Telegram/Telegram.exe
